### ISSUE TITLE
无法引用pyalgo

### ISSUE THREAD

**Issue by memelan** [Bohr1005/xcrypto#14]
如题，是不是需要python setup.py install 一类的呀。按照目前的文件结构，python下的example代码似乎是无法运行debug的。不太熟悉rust，混编项目如何debug和继续开发（infra or strat）呢？

**Comment by Bohr1005** [comment]
是的，需要在pyalgo的项目目录下，通过maturin这个脚手架来安装，所以需要提前安装好maturin，通过pip install maturin来安装。然后在pyalgo目录下执行maturin develop -r安装release版本的pyalgo

**Comment by memelan** [comment]
多谢，明白了。

请问在路径.../xcrypto/binance 下执行：
 ./spot -c=spot.json -l=info 这一步报错：
zsh: permission denied: ./spot

这里是需要sudo权限吗？例如：
sudo ./spot -c=spot.json -l=info
或者需要有其他的设置？
readme里其他的配置都做了。
谢谢。

**Comment by Bohr1005** [comment]
> 多谢，明白了。
> 
> 请问在路径.../xcrypto/binance 下执行： ./spot -c=spot.json -l=info 这一步报错： zsh: permission denied: ./spot
> 
> 这里是需要sudo权限吗？例如： sudo ./spot -c=spot.json -l=info 或者需要有其他的设置？ readme里其他的配置都做了。 谢谢。

xcrypto/binance下的是源码，如果交易现货就进入spot这个文件夹里，执行cargo build -r，编译出来的二进制文件会在target/release目录下，运行这个目录下的spot程序就可以了，会有一个-c的参数，是传你的配置文件，如果交易u本位期货，就编译usdt这个目录下的文件，编译出来的可执行文件也会放在target/release目录下，运行方式和spot的一样

**Comment by WAYNECKTANG** [comment]
请问执行demo时遇到以下error应如何处理？谢谢
`thread '<unnamed>' panicked at pyalgo/src/session.rs:225:35:
called `Result::unwrap()` on an `Err` value: WebSocketError: I/O failure

Caused by:
    Connection refused (os error 61)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by Bohr1005** [comment]
> 请问执行demo时遇到以下error应如何处理？谢谢 `thread '<unnamed>' panicked at pyalgo/src/session.rs:225:35: called `Result::unwrap()`on an`Err` value: WebSocketError: I/O failure
> 
> Caused by: Connection refused (os error 61) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

这个是连接交易所那边失败了，应该是你在国内所以连不上，试试先找个vpn再连，或者找个境外的机器就没问题了
